function Meta = read_ACE_GLC_meta(filename)
%IMPORTFILE Import data from a text file
%  ACE = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a cell array.
%
%  ACE = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  ace = importfile("C:\Data\ACE\v5.2\GLC\ACE-FTS_L2_v5.2_GLC\ACE-FTS_L2_v5.2_GLC\2014\ace.sr55939.txt", [1, 5]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Sep-2023 19:12:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
  dataLines = [1, 5];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["OCCULTATION_NAME", "acesr55939", "VarName3", "Var4", "Var5"];
opts.SelectedVariableNames = ["OCCULTATION_NAME", "acesr55939", "VarName3"];
opts.VariableTypes = ["char", "char", "char", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["OCCULTATION_NAME", "acesr55939", "VarName3", "Var4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["OCCULTATION_NAME", "acesr55939", "VarName3", "Var4", "Var5"], "EmptyFieldRule", "auto");

% Import the data
ace = readtable(filename, opts);

%% Convert to output type
ace = table2cell(ace);
numIdx = cellfun(@(x) ~isnan(str2double(x)), ace);
ace(numIdx) = cellfun(@(x) {str2double(x)}, ace(numIdx));


%parse into something useful
Meta.FileID = ace{1,2};

Meta.Time   = datenum(ace{2,2},'YYYY-mm-dd');
a = ace{2,3};
h = str2num(a(1:2))./24;
m = str2num(a(4:5))./(24*60);
s = str2num(a(7:8))./(24*60*60);
Meta.Time = Meta.Time+h+m+s;
Meta.Beta = ace{5,2};

end
