function [z, P, T, Lat, Lon] = read_ace_GLC(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [Z, P, T, LAT, LON] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [Z, P, T, LAT, LON] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [z, P, T, Lat, Lon] = importfile("C:\Data\ACE\v5.2\GLC\ACE-FTS_L2_v5.2_GLC\ACE-FTS_L2_v5.2_GLC\2009\ace.sr29009.txt", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Sep-2023 18:54:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
  dataLines = [8, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["z", "P", "T", "Lat", "Lon"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
z = tbl.z;
P = tbl.P;
T = tbl.T;
Lat = tbl.Lat;
Lon = tbl.Lon;
end
